# Generated by Django 2.0rc1 on 2017-11-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amtesting_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='topic',
            new_name='topic_name',
        ),
    ]
