# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0002_auto_20171129_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemUser',
            new_name='SystemUsers',
        ),
    ]
